services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - default
  web-server:
    image: ryann3/lablup-chat-web-server:1.0
    container_name: web-server
    ports:
      - 3000:3000
    stdin_open: true
    networks:
      - default
    restart: always
  was-server:
    image: ryann3/lablup-chat-was-server:1.0
    container_name: was-server
    ports:
      - 8080:8080
    stdin_open: true
    networks:
      - default
    restart: always
networks:
  default:
    name: lablup-network
