services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - default
  web-server:
    build:
      context: ./WEB/
      dockerfile: ./Dockerfile
    platform: linux/amd64
    container_name: web-server
    ports:
      - 3000:3000
    stdin_open: true
    networks:
      - default
  was-server:
    build:
      context: ./WAS/
      dockerfile: ./Dockerfile
    platform: linux/amd64
    container_name: was-server
    ports:
      - 8080:8080
    volumes:
      - .:/server
    environment:
      REDIS_ADDR: redis://redis:6379
    stdin_open: true
    networks:
      - default
networks:
  default:
    name: lablup-network
